# Generated by Django 2.0.4 on 2018-05-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_of_post',
            new_name='date',
        ),
    ]
