# Generated by Django 2.0.4 on 2018-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of_post',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
