# Generated by Django 2.0.4 on 2018-05-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Network', '0004_auto_20180430_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_post',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
